.

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -25,8 +25,18 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
           
-      - name: Set up Google Cloud credentials
-        run: echo "#### MY SECRET IS ${{ secrets.DOCKERHUB_USERNAME }}"
+      - name: Create Google Cloud credentials file
+        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/google-credentials.json
+
+      - name: Verify Google Cloud credentials file
+        run: |
+          if [ ! -f google-credentials.json ]; then
+            echo "google-credentials.json file is missing!"
+            exit 1
+          else
+            echo "google-credentials.json file is present."
+            cat google-credentials.json
+          fi
         
       # - name: Set up environment variable for Firebase
       #   run: echo "GOOGLE_APPLICATION_CREDENTIALS_JSON=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" >> $GITHUB_ENV
@@ -46,10 +56,8 @@ jobs:
           file: ./docker/migration/Dockerfile
           push: true
           tags: markvovn/dentistry-be-migration:latest
-
-          build-args: |
-            GOOGLE_APPLICATION_CREDENTIALS_JSON=HELLO_WORLD
-
+          secrets: |
+            id=google_application_credentials,src=/tmp/google-credentials.json
 
   update_server:
       name: Updating prod environment
diff --git a/docker/migration/Dockerfile b/docker/migration/Dockerfile
--- a/docker/migration/Dockerfile
+++ b/docker/migration/Dockerfile
@@ -14,9 +14,11 @@ COPY DentistryRepositories/*.csproj ./DentistryRepositories/
 COPY DentistryServices/*.csproj ./DentistryServices/
 COPY Search/*.csproj ./Search/
 COPY Firebase/*.csproj ./Firebase/
-COPY prn-dentistry/Config/*.json ./prn-dentistry/Config/
+# COPY prn-dentistry/Config/*.json ./prn-dentistry/Config/
 COPY prn-dentistry/*.csproj ./prn-dentistry/
 RUN dotnet restore --use-current-runtime
+
+COPY google-credentials.json ./prn-dentistry/Config/google-credentials.json
 
 # Copy everything else and build
 COPY . ./
@@ -27,8 +29,10 @@ RUN apt-get install -y make
 ENV PATH="$PATH:/root/.dotnet/tools"
 RUN dotnet tool install --version 7.0.19 --global dotnet-ef
 
-RUN ls -al 
-RUN echo '################## ${GOOGLE_APPLICATION_CREDENTIALS_JSON}'
+RUN if [ ! -f ./prn-dentistry/Config/google-credentials.json ]; then echo "google-credentials.json is missing!" && exit 1; else echo "google-credentials.json is present."; fi
+
+# RUN ls -al 
+# RUN echo '################## ${GOOGLE_APPLICATION_CREDENTIALS_JSON}'
 
 RUN dotnet ef migrations bundle --force --project prn-dentistry -r linux-x64 --verbose --self-contained --output efbundle
 
